/** Incident detail: what happened, where, how many, what evidence, who acknowledged. */
import type { IncidentDetail as Detail } from "../lib/api";
import { peopleLabel, relativeTime } from "../lib/api";
import { AttachmentMedia } from "./AttachmentMedia";
import { LanguageBadge, PriorityBadge, StatusBadge, VerificationBadge } from "./Badges";

export function IncidentDetailPanel({ detail }: { detail: Detail }) {
  const { incident, attachments, dispatch } = detail;
  const redacted = incident.redacted ?? [];

  return (
    <div>
      <h2>Incident</h2>
      <div className="detail-head">
        <PriorityBadge priority={incident.priority_class} />
        <StatusBadge status={detail.status} />
        <VerificationBadge status={incident.verification_status} />
        <LanguageBadge incident={incident} />
      </div>

      <p className="original-text">{incident.original_text}</p>
      <p className="provenance">
        Original report from {incident.source_node_id} · {relativeTime(incident.reported_at)}
        {redacted.length > 0 && ` · restricted fields hidden: ${redacted.join(", ")}`}
      </p>

      <dl className="facts">
        <div className="fact">
          <dt>People affected</dt>
          <dd>{peopleLabel(incident.people_affected)}</dd>
        </div>
        <div className="fact">
          <dt>Category</dt>
          <dd>{incident.disaster_types.join(", ") || "Unclassified"}</dd>
        </div>
        <div className="fact">
          <dt>Location</dt>
          <dd>
            {incident.location
              ? `${incident.location.latitude.toFixed(4)}, ${incident.location.longitude.toFixed(4)}${
                  incident.location.shared_precisely ? "" : " (approx.)"
                }`
              : "Not shared"}
          </dd>
        </div>
        <div className="fact">
          <dt>Evidence</dt>
          <dd>{attachments.length}</dd>
        </div>
      </dl>

      <section className="section">
        <h3>AI analysis</h3>
        <div className="ai-panel">
          <strong>
            AI suggestion — urgency {incident.urgency}, severity {incident.severity}, confidence{" "}
            {(incident.classification_confidence * 100).toFixed(0)}%
          </strong>
          <ul>
            {incident.priority_explanation.length > 0 ? (
              incident.priority_explanation.map((line, index) => <li key={index}>{line}</li>)
            ) : (
              <li>No explanation recorded for this incident.</li>
            )}
          </ul>
          <p className="simulated-note">
            Generated by the classifier and the deterministic policy engine. A human decides.
          </p>
        </div>
      </section>

      <section className="section">
        <h3>Evidence</h3>
        {attachments.length === 0 ? (
          <p className="empty">No attachments received yet. Text arrives before media.</p>
        ) : (
          <div className="evidence">
            {attachments.map((file) => (
              <AttachmentMedia key={file.id} incidentId={incident.id} file={file} />
            ))}
          </div>
        )}
      </section>

      <section className="section">
        <h3>Dispatch history</h3>
        {dispatch.length === 0 ? (
          <p className="empty">Nothing dispatched. Dispatch requires explicit confirmation.</p>
        ) : (
          <div className="evidence">
            {dispatch.map((order) => (
              <div className="evidence-row" key={order.id}>
                <span>{order.resource_id}</span>
                <StatusBadge status={order.status} />
                <span className="badge outline">simulated</span>
                {order.authorized_by && <span>by {order.authorized_by}</span>}
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
