/** Incident detail: hero-first layout. Text dominant, metadata compact, AI separated. */
import { lazy, Suspense } from "react";

import { usePrefersReducedMotion } from "../hooks/useLocalStorageState";
import type { IncidentDetail as Detail } from "../lib/api";
import { peopleLabel, relativeTime } from "../lib/api";
import { AttachmentMedia } from "./AttachmentMedia";
import { LanguageBadge, PriorityBadge, StatusBadge, VerificationBadge } from "./Badges";
import { CoordinatorNotes } from "./CoordinatorNotes";

// maplibre-gl is ~1MB — this is emergency-response software where the queue
// and incident detail must render instantly, so the map (same reasoning as
// the storm background) is code-split and never blocks first paint.
const LocationMap = lazy(() =>
  import("./LocationMap").then((m) => ({ default: m.LocationMap })),
);

export function IncidentDetailPanel({
  detail,
  onNotesChanged,
}: {
  detail: Detail;
  onNotesChanged?: () => void;
}) {
  const { incident, attachments, dispatch, notes } = detail;
  const redacted = incident.redacted ?? [];
  const reducedMotion = usePrefersReducedMotion();

  return (
    <div>
      {/* Kicker — incident type */}
      <p className="detail-kicker">
        {incident.disaster_types.join(" / ") || "UNCLASSIFIED"} · INCIDENT REPORT
      </p>

      {/* Badges */}
      <div className="detail-head">
        <PriorityBadge priority={incident.priority_class} />
        <StatusBadge status={detail.status} />
        <VerificationBadge status={incident.verification_status} />
        <LanguageBadge incident={incident} />
      </div>

      {/* Hero text — the most important thing */}
      <div className="original-text">
        {incident.original_text}
      </div>
      <p className="provenance">
        Source: {incident.source_node_id} · {relativeTime(incident.reported_at)}
        {redacted.length > 0 && ` · restricted: ${redacted.join(", ")}`}
      </p>

      {/* Compact metadata strip */}
      <dl className="facts">
        <div className="fact">
          <dt>People</dt>
          <dd>{peopleLabel(incident.people_affected)}</dd>
        </div>
        <div className="fact">
          <dt>Category</dt>
          <dd>{incident.disaster_types.join(", ") || "Unclassified"}</dd>
        </div>
        <div className="fact">
          {incident.location && <div className="fact-radar" aria-hidden="true" />}
          {incident.location && !reducedMotion && (
            <div className="fact-radar-sweep" aria-hidden="true" />
          )}
          <dt>Location</dt>
          <dd>
            {incident.location
              ? `${incident.location.latitude.toFixed(4)}, ${incident.location.longitude.toFixed(4)}${
                  incident.location.shared_precisely ? "" : " (approx)"
                }`
              : "Not shared"}
          </dd>
        </div>
        <div className="fact">
          <dt>Evidence</dt>
          <dd>{attachments.length}</dd>
        </div>
      </dl>

      {/* Location map — the phone's real coordinates, plotted */}
      <Suspense fallback={<section className="section"><h3>Location</h3><p className="empty">Loading map…</p></section>}>
        <LocationMap location={incident.location} />
      </Suspense>

      {/* AI Incident Intelligence */}
      <section className="section">
        <h3>AI Incident Intelligence</h3>
        <div className="ai-panel tech-corners">
          <span className="badge-edge-overlap badge ai" style={{ fontSize: "10px", padding: "2px 8px" }}>
            AI TRIAGE · SYSTEM 1.2
          </span>
          <div className="ai-panel-head">
            <span className="status-dot" aria-hidden="true" />
            Classifier Active · System Suggestion
          </div>

          {incident.classification_confidence < 0.4 && (
            <span className="low-confidence-flag">Human decision required</span>
          )}

          <dl className="ai-stats">
            <div className="ai-stat">
              <dt>Urgency</dt>
              <dd>{incident.urgency}</dd>
            </div>
            <div className="ai-stat">
              <dt>Severity</dt>
              <dd>{incident.severity}</dd>
            </div>
          </dl>

          <ul>
            {incident.priority_explanation.length > 0 ? (
              incident.priority_explanation.map((line, index) => <li key={index}>{line}</li>)
            ) : (
              <li>No explanation recorded for this incident.</li>
            )}
          </ul>

          <div className="decision-strip">
            <span className="decision-ai">AI PROPOSES</span>
            <span className="decision-sep">·</span>
            <span className="decision-human">HUMAN DECIDES</span>
          </div>

          <p className="simulated-note">
            Generated by classifier + deterministic policy engine.
          </p>
        </div>
      </section>

      {/* Evidence console */}
      <section className="section">
        <h3>Evidence Console</h3>
        {attachments.length === 0 ? (
          <p className="empty">No evidence received — text arrives before media</p>
        ) : (
          <div className="evidence">
            {attachments.map((file, idx) => (
              <div key={file.id} className="evidence-item">
                <div className="evidence-item-head">
                  <span className="evidence-id">
                    EVIDENCE_{String(idx + 1).padStart(3, "0")}
                  </span>
                  {file.verified && (
                    <span className="evidence-verified">✓ VERIFIED</span>
                  )}
                </div>
                <AttachmentMedia incidentId={incident.id} file={file} />
              </div>
            ))}
          </div>
        )}
      </section>

      {/* Coordinator notes */}
      <CoordinatorNotes
        incidentId={incident.id}
        notes={notes}
        onAdded={() => onNotesChanged?.()}
      />

      {/* Dispatch timeline */}
      <section className="section">
        <h3>Dispatch Timeline</h3>
        {(() => {
          const acknowledged = [
            "ACKNOWLEDGED", "DISPATCH_REQUESTED", "DISPATCHED", "EN_ROUTE", "ARRIVED", "RESOLVED",
          ].includes(detail.status);
          const dispatched = dispatch.length > 0;
          const resolved = detail.status === "RESOLVED";
          return (
            <ul className="timeline">
              <li className="timeline-node reached">Incident received</li>
              <li className={`timeline-node ${acknowledged ? "reached" : "pending"}`}>
                Human acknowledgement
              </li>
              <li className={`timeline-node ${dispatched ? "reached" : "pending"}`}>
                Resource dispatch
                {dispatched ? ` — ${dispatch.length} order${dispatch.length > 1 ? "s" : ""}` : ""}
              </li>
              <li className={`timeline-node ${resolved ? "reached" : "pending"}`}>
                Incident resolved
              </li>
            </ul>
          );
        })()}

        {dispatch.length > 0 && (
          <div className="evidence" style={{ marginTop: "var(--s3)" }}>
            {dispatch.map((order) => (
              <div className="evidence-row" key={order.id}>
                <span style={{ fontFamily: "var(--font-mono)", fontSize: "11px" }}>
                  {order.resource_id}
                </span>
                <StatusBadge status={order.status} />
                <span className="badge outline">simulated</span>
                {order.authorized_by && (
                  <span style={{ fontSize: "11px", color: "var(--text-dim)" }}>
                    by {order.authorized_by}
                  </span>
                )}
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
